// Generated from assets/skins/classic/manifest.json by scripts/design/bundle_skin.py.
pub(super) const PNGS: &[(&str, &[u8])] = &[
    (
        "1/mask-button-active-0",
        include_bytes!("../../assets/skins/classic/1x/mask-button-active-0.png"),
    ),
    (
        "1/mask-button-active-1",
        include_bytes!("../../assets/skins/classic/1x/mask-button-active-1.png"),
    ),
    (
        "1/mask-button-active-2",
        include_bytes!("../../assets/skins/classic/1x/mask-button-active-2.png"),
    ),
    (
        "1/mask-button-active-3",
        include_bytes!("../../assets/skins/classic/1x/mask-button-active-3.png"),
    ),
    (
        "1/mask-button-active-4",
        include_bytes!("../../assets/skins/classic/1x/mask-button-active-4.png"),
    ),
    (
        "1/mask-button-active-5",
        include_bytes!("../../assets/skins/classic/1x/mask-button-active-5.png"),
    ),
    (
        "1/mask-button-disabled-0",
        include_bytes!("../../assets/skins/classic/1x/mask-button-disabled-0.png"),
    ),
    (
        "1/mask-button-disabled-1",
        include_bytes!("../../assets/skins/classic/1x/mask-button-disabled-1.png"),
    ),
    (
        "1/mask-button-disabled-2",
        include_bytes!("../../assets/skins/classic/1x/mask-button-disabled-2.png"),
    ),
    (
        "1/mask-button-disabled-3",
        include_bytes!("../../assets/skins/classic/1x/mask-button-disabled-3.png"),
    ),
    (
        "1/mask-button-disabled-4",
        include_bytes!("../../assets/skins/classic/1x/mask-button-disabled-4.png"),
    ),
    (
        "1/mask-button-disabled-5",
        include_bytes!("../../assets/skins/classic/1x/mask-button-disabled-5.png"),
    ),
    (
        "1/mask-button-focus-0",
        include_bytes!("../../assets/skins/classic/1x/mask-button-focus-0.png"),
    ),
    (
        "1/mask-button-focus-1",
        include_bytes!("../../assets/skins/classic/1x/mask-button-focus-1.png"),
    ),
    (
        "1/mask-button-focus-2",
        include_bytes!("../../assets/skins/classic/1x/mask-button-focus-2.png"),
    ),
    (
        "1/mask-button-focus-3",
        include_bytes!("../../assets/skins/classic/1x/mask-button-focus-3.png"),
    ),
    (
        "1/mask-button-focus-4",
        include_bytes!("../../assets/skins/classic/1x/mask-button-focus-4.png"),
    ),
    (
        "1/mask-button-focus-5",
        include_bytes!("../../assets/skins/classic/1x/mask-button-focus-5.png"),
    ),
    (
        "1/mask-button-focus-6",
        include_bytes!("../../assets/skins/classic/1x/mask-button-focus-6.png"),
    ),
    (
        "1/mask-button-hover-0",
        include_bytes!("../../assets/skins/classic/1x/mask-button-hover-0.png"),
    ),
    (
        "1/mask-button-hover-1",
        include_bytes!("../../assets/skins/classic/1x/mask-button-hover-1.png"),
    ),
    (
        "1/mask-button-hover-2",
        include_bytes!("../../assets/skins/classic/1x/mask-button-hover-2.png"),
    ),
    (
        "1/mask-button-hover-3",
        include_bytes!("../../assets/skins/classic/1x/mask-button-hover-3.png"),
    ),
    (
        "1/mask-button-hover-4",
        include_bytes!("../../assets/skins/classic/1x/mask-button-hover-4.png"),
    ),
    (
        "1/mask-button-hover-5",
        include_bytes!("../../assets/skins/classic/1x/mask-button-hover-5.png"),
    ),
    (
        "1/mask-button-normal-0",
        include_bytes!("../../assets/skins/classic/1x/mask-button-normal-0.png"),
    ),
    (
        "1/mask-button-normal-1",
        include_bytes!("../../assets/skins/classic/1x/mask-button-normal-1.png"),
    ),
    (
        "1/mask-button-normal-2",
        include_bytes!("../../assets/skins/classic/1x/mask-button-normal-2.png"),
    ),
    (
        "1/mask-button-normal-3",
        include_bytes!("../../assets/skins/classic/1x/mask-button-normal-3.png"),
    ),
    (
        "1/mask-button-normal-4",
        include_bytes!("../../assets/skins/classic/1x/mask-button-normal-4.png"),
    ),
    (
        "1/mask-button-normal-5",
        include_bytes!("../../assets/skins/classic/1x/mask-button-normal-5.png"),
    ),
    (
        "1/mask-button-pressed-0",
        include_bytes!("../../assets/skins/classic/1x/mask-button-pressed-0.png"),
    ),
    (
        "1/mask-button-pressed-1",
        include_bytes!("../../assets/skins/classic/1x/mask-button-pressed-1.png"),
    ),
    (
        "1/mask-button-pressed-2",
        include_bytes!("../../assets/skins/classic/1x/mask-button-pressed-2.png"),
    ),
    (
        "1/mask-button-pressed-3",
        include_bytes!("../../assets/skins/classic/1x/mask-button-pressed-3.png"),
    ),
    (
        "1/mask-button-pressed-4",
        include_bytes!("../../assets/skins/classic/1x/mask-button-pressed-4.png"),
    ),
    (
        "1/mask-button-pressed-5",
        include_bytes!("../../assets/skins/classic/1x/mask-button-pressed-5.png"),
    ),
    (
        "1/mask-panel-0",
        include_bytes!("../../assets/skins/classic/1x/mask-panel-0.png"),
    ),
    (
        "1/mask-panel-1",
        include_bytes!("../../assets/skins/classic/1x/mask-panel-1.png"),
    ),
    (
        "1/mask-panel-2",
        include_bytes!("../../assets/skins/classic/1x/mask-panel-2.png"),
    ),
    (
        "1/mask-panel-3",
        include_bytes!("../../assets/skins/classic/1x/mask-panel-3.png"),
    ),
    (
        "1/mask-panel-4",
        include_bytes!("../../assets/skins/classic/1x/mask-panel-4.png"),
    ),
    (
        "1/mask-panel-5",
        include_bytes!("../../assets/skins/classic/1x/mask-panel-5.png"),
    ),
    (
        "1/mask-panel-rigid-0",
        include_bytes!("../../assets/skins/classic/1x/mask-panel-rigid-0.png"),
    ),
    (
        "1/mask-panel-rigid-1",
        include_bytes!("../../assets/skins/classic/1x/mask-panel-rigid-1.png"),
    ),
    (
        "1/mask-panel-rigid-2",
        include_bytes!("../../assets/skins/classic/1x/mask-panel-rigid-2.png"),
    ),
    (
        "1/mask-panel-rigid-3",
        include_bytes!("../../assets/skins/classic/1x/mask-panel-rigid-3.png"),
    ),
    (
        "1/mask-panel-rigid-4",
        include_bytes!("../../assets/skins/classic/1x/mask-panel-rigid-4.png"),
    ),
    (
        "1/mask-panel-rigid-5",
        include_bytes!("../../assets/skins/classic/1x/mask-panel-rigid-5.png"),
    ),
    (
        "1/mask-well-0",
        include_bytes!("../../assets/skins/classic/1x/mask-well-0.png"),
    ),
    (
        "1/mask-well-1",
        include_bytes!("../../assets/skins/classic/1x/mask-well-1.png"),
    ),
    (
        "1/mask-well-2",
        include_bytes!("../../assets/skins/classic/1x/mask-well-2.png"),
    ),
    (
        "1/mask-well-3",
        include_bytes!("../../assets/skins/classic/1x/mask-well-3.png"),
    ),
    (
        "2/mask-button-active-0",
        include_bytes!("../../assets/skins/classic/2x/mask-button-active-0.png"),
    ),
    (
        "2/mask-button-active-1",
        include_bytes!("../../assets/skins/classic/2x/mask-button-active-1.png"),
    ),
    (
        "2/mask-button-active-2",
        include_bytes!("../../assets/skins/classic/2x/mask-button-active-2.png"),
    ),
    (
        "2/mask-button-active-3",
        include_bytes!("../../assets/skins/classic/2x/mask-button-active-3.png"),
    ),
    (
        "2/mask-button-active-4",
        include_bytes!("../../assets/skins/classic/2x/mask-button-active-4.png"),
    ),
    (
        "2/mask-button-active-5",
        include_bytes!("../../assets/skins/classic/2x/mask-button-active-5.png"),
    ),
    (
        "2/mask-button-disabled-0",
        include_bytes!("../../assets/skins/classic/2x/mask-button-disabled-0.png"),
    ),
    (
        "2/mask-button-disabled-1",
        include_bytes!("../../assets/skins/classic/2x/mask-button-disabled-1.png"),
    ),
    (
        "2/mask-button-disabled-2",
        include_bytes!("../../assets/skins/classic/2x/mask-button-disabled-2.png"),
    ),
    (
        "2/mask-button-disabled-3",
        include_bytes!("../../assets/skins/classic/2x/mask-button-disabled-3.png"),
    ),
    (
        "2/mask-button-disabled-4",
        include_bytes!("../../assets/skins/classic/2x/mask-button-disabled-4.png"),
    ),
    (
        "2/mask-button-disabled-5",
        include_bytes!("../../assets/skins/classic/2x/mask-button-disabled-5.png"),
    ),
    (
        "2/mask-button-focus-0",
        include_bytes!("../../assets/skins/classic/2x/mask-button-focus-0.png"),
    ),
    (
        "2/mask-button-focus-1",
        include_bytes!("../../assets/skins/classic/2x/mask-button-focus-1.png"),
    ),
    (
        "2/mask-button-focus-2",
        include_bytes!("../../assets/skins/classic/2x/mask-button-focus-2.png"),
    ),
    (
        "2/mask-button-focus-3",
        include_bytes!("../../assets/skins/classic/2x/mask-button-focus-3.png"),
    ),
    (
        "2/mask-button-focus-4",
        include_bytes!("../../assets/skins/classic/2x/mask-button-focus-4.png"),
    ),
    (
        "2/mask-button-focus-5",
        include_bytes!("../../assets/skins/classic/2x/mask-button-focus-5.png"),
    ),
    (
        "2/mask-button-focus-6",
        include_bytes!("../../assets/skins/classic/2x/mask-button-focus-6.png"),
    ),
    (
        "2/mask-button-hover-0",
        include_bytes!("../../assets/skins/classic/2x/mask-button-hover-0.png"),
    ),
    (
        "2/mask-button-hover-1",
        include_bytes!("../../assets/skins/classic/2x/mask-button-hover-1.png"),
    ),
    (
        "2/mask-button-hover-2",
        include_bytes!("../../assets/skins/classic/2x/mask-button-hover-2.png"),
    ),
    (
        "2/mask-button-hover-3",
        include_bytes!("../../assets/skins/classic/2x/mask-button-hover-3.png"),
    ),
    (
        "2/mask-button-hover-4",
        include_bytes!("../../assets/skins/classic/2x/mask-button-hover-4.png"),
    ),
    (
        "2/mask-button-hover-5",
        include_bytes!("../../assets/skins/classic/2x/mask-button-hover-5.png"),
    ),
    (
        "2/mask-button-normal-0",
        include_bytes!("../../assets/skins/classic/2x/mask-button-normal-0.png"),
    ),
    (
        "2/mask-button-normal-1",
        include_bytes!("../../assets/skins/classic/2x/mask-button-normal-1.png"),
    ),
    (
        "2/mask-button-normal-2",
        include_bytes!("../../assets/skins/classic/2x/mask-button-normal-2.png"),
    ),
    (
        "2/mask-button-normal-3",
        include_bytes!("../../assets/skins/classic/2x/mask-button-normal-3.png"),
    ),
    (
        "2/mask-button-normal-4",
        include_bytes!("../../assets/skins/classic/2x/mask-button-normal-4.png"),
    ),
    (
        "2/mask-button-normal-5",
        include_bytes!("../../assets/skins/classic/2x/mask-button-normal-5.png"),
    ),
    (
        "2/mask-button-pressed-0",
        include_bytes!("../../assets/skins/classic/2x/mask-button-pressed-0.png"),
    ),
    (
        "2/mask-button-pressed-1",
        include_bytes!("../../assets/skins/classic/2x/mask-button-pressed-1.png"),
    ),
    (
        "2/mask-button-pressed-2",
        include_bytes!("../../assets/skins/classic/2x/mask-button-pressed-2.png"),
    ),
    (
        "2/mask-button-pressed-3",
        include_bytes!("../../assets/skins/classic/2x/mask-button-pressed-3.png"),
    ),
    (
        "2/mask-button-pressed-4",
        include_bytes!("../../assets/skins/classic/2x/mask-button-pressed-4.png"),
    ),
    (
        "2/mask-button-pressed-5",
        include_bytes!("../../assets/skins/classic/2x/mask-button-pressed-5.png"),
    ),
    (
        "2/mask-panel-0",
        include_bytes!("../../assets/skins/classic/2x/mask-panel-0.png"),
    ),
    (
        "2/mask-panel-1",
        include_bytes!("../../assets/skins/classic/2x/mask-panel-1.png"),
    ),
    (
        "2/mask-panel-2",
        include_bytes!("../../assets/skins/classic/2x/mask-panel-2.png"),
    ),
    (
        "2/mask-panel-3",
        include_bytes!("../../assets/skins/classic/2x/mask-panel-3.png"),
    ),
    (
        "2/mask-panel-4",
        include_bytes!("../../assets/skins/classic/2x/mask-panel-4.png"),
    ),
    (
        "2/mask-panel-5",
        include_bytes!("../../assets/skins/classic/2x/mask-panel-5.png"),
    ),
    (
        "2/mask-panel-rigid-0",
        include_bytes!("../../assets/skins/classic/2x/mask-panel-rigid-0.png"),
    ),
    (
        "2/mask-panel-rigid-1",
        include_bytes!("../../assets/skins/classic/2x/mask-panel-rigid-1.png"),
    ),
    (
        "2/mask-panel-rigid-2",
        include_bytes!("../../assets/skins/classic/2x/mask-panel-rigid-2.png"),
    ),
    (
        "2/mask-panel-rigid-3",
        include_bytes!("../../assets/skins/classic/2x/mask-panel-rigid-3.png"),
    ),
    (
        "2/mask-panel-rigid-4",
        include_bytes!("../../assets/skins/classic/2x/mask-panel-rigid-4.png"),
    ),
    (
        "2/mask-panel-rigid-5",
        include_bytes!("../../assets/skins/classic/2x/mask-panel-rigid-5.png"),
    ),
    (
        "2/mask-well-0",
        include_bytes!("../../assets/skins/classic/2x/mask-well-0.png"),
    ),
    (
        "2/mask-well-1",
        include_bytes!("../../assets/skins/classic/2x/mask-well-1.png"),
    ),
    (
        "2/mask-well-2",
        include_bytes!("../../assets/skins/classic/2x/mask-well-2.png"),
    ),
    (
        "2/mask-well-3",
        include_bytes!("../../assets/skins/classic/2x/mask-well-3.png"),
    ),
];
